### ISSUE TITLE
Error Parsing the configuration file

### ISSUE THREAD

**Issue by Gona2119** [paukstelis/octoprint_deploy#102]
Wassup, yesterday I've installed octoprint deploy in a tv box with Armbian, all was ok until I reboot the box 2 times approximately and then OctoPrint web server never started up again, this is the terminal output:

` octo:~:% sudo systemctl status NebulaPlus
● NebulaPlus.service - The snappy web interface for your 3D printer
   Loaded: loaded (/etc/systemd/system/NebulaPlus.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2023-07-12 17:31:24 UTC; 10min ago
  Process: 737 ExecStart=/home/gona/OctoPrint/bin/octoprint serve --config=${CONFIGFILE} --basedir=${BASEDIR} --port=${P Main PID: 737 (code=exited, status=0/SUCCESS)

Jul 12 17:30:40 octo systemd[1]: Started The snappy web interface for your 3D printer.
Jul 12 17:31:23 octo octoprint[737]: 2023-07-12 17:31:23,494 - octoprint.startup - CRITICAL - Could not initialize settiJul 12 17:31:23 octo octoprint[737]: 2023-07-12 17:31:23,498 - octoprint.startup - CRITICAL - There was a fatal error stJul 12 17:31:23 octo octoprint[737]: Could not initialize settings manager: Error parsing the configuration file /home/gJul 12 17:31:23 octo octoprint[737]: There was a fatal error starting up OctoPrint.
Jul 12 17:31:24 octo systemd[1]: NebulaPlus.service: Succeeded. `

Any ideas of how to solve it or what to do? Ty sir and nice script btw :)

**Comment by paukstelis** [comment]
> Wassup, yesterday I've installed octoprint deploy in a tv box with Armbian, all was ok until I reboot the box 2 times approximately and then OctoPrint web server never started up again, this is the terminal output: ` octo:~:% sudo systemctl status NebulaPlus ● NebulaPlus.service - The snappy web interface for your 3D printer Loaded: loaded (/etc/systemd/system/NebulaPlus.service; enabled; vendor preset: enabled) Active: inactive (dead) since Wed 2023-07-12 17:31:24 UTC; 10min ago Process: 737 ExecStart=/home/gona/OctoPrint/bin/octoprint serve --config=${CONFIGFILE} --basedir=${BASEDIR} --port=${P Main PID: 737 (code=exited, status=0/SUCCESS)
> 
> Jul 12 17:30:40 octo systemd[1]: Started The snappy web interface for your 3D printer. Jul 12 17:31:23 octo octoprint[737]: 2023-07-12 17:31:23,494 - octoprint.startup - CRITICAL - Could not initialize settiJul 12 17:31:23 octo octoprint[737]: 2023-07-12 17:31:23,498 - octoprint.startup - CRITICAL - There was a fatal error stJul 12 17:31:23 octo octoprint[737]: Could not initialize settings manager: Error parsing the configuration file /home/gJul 12 17:31:23 octo octoprint[737]: There was a fatal error starting up OctoPrint. Jul 12 17:31:24 octo systemd[1]: NebulaPlus.service: Succeeded. `
> 
> Any ideas of how to solve it or what to do? Ty sir and nice script btw :)

Here are a couple of commands to start with:
`cat /etc/systemd/system/NebulaPlus.service`
`ls -la ~/.NebulaPlus`
`cat ~/.NebulaPlus/config.yaml`

**Comment by Gona2119** [comment]
Right now i've restored a backup that was created 20 minutes after the octoprint installation and all seems good, webserver started and the 3 commands that you send me worked flawlessly. Hope this solution lasts at least one day.  Another question is if you know why I can't install OctoEverywhere plugin, when it finishes the download process the popup message says reboot to install unknown or something like that, after a reboot the plugin isn't installed
