### ISSUE TITLE
Error upon instance creation

### ISSUE THREAD

**Issue by wesalmon** [paukstelis/octoprint_deploy#104]
I have tried the script on a rock64 and orangepi 2 with the same error each time.

Plug your printer in via USB now (detection time-out in 1 min)
Serial number detected as: AG0KEBVM
No duplicate serial number detected.

Would you like to auto detect an associated USB camera (experimental)? [y/n]: n
Ready to write all changes. Do you want to proceed? [y/n]: y
Uniquifying instance...
sudo: unrecognized option '--basedir'
usage: sudo -h | -K | -k | -V
usage: sudo -v [-ABknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-ABknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-ABbEHknPS] [-r role] [-t type] [-C num] [-D directory] [-g group]
            [-h host] [-p prompt] [-R directory] [-T timeout] [-u user]
            [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-ABknS] [-r role] [-t type] [-C num] [-D directory] [-g group]
            [-h host] [-p prompt] [-R directory] [-T timeout] [-u user] file ...
sudo: unrecognized option '--basedir'

Any idea what I am missing?  I have tried to respond yes and no to camera with the same results.
Thank you!

**Comment by paukstelis** [comment]
This means that OctoPrint itself has not been installed.
Can you provide the full output from the beginning of the system preparation?

**Comment by wesalmon** [comment]
You are correct!  This error never came up before:
  File "/usr/lib/python3.10/venv/__main__.py", line 6, in <module>
    main()
  File "/usr/lib/python3.10/venv/__init__.py", line 525, in main
    builder.create(d)
  File "/usr/lib/python3.10/venv/__init__.py", line 75, in create
    self._setup_pip(context)
  File "/usr/lib/python3.10/venv/__init__.py", line 318, in _setup_pip
    subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1139, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt
sudo: /home/admin/OctoPrint/bin/pip: command not found
sudo: /home/admin/OctoPrint/bin/pip: command not found
sudo: /home/admin/OctoPrint/bin/pip: command not found
WARNING! WARNING! WARNING!
OctoPrint has not been installed correctly.
Please answer Y to remove everything and try running prepare system again.
Remove everything? [y/n]:

This happens on 2 different boards with new installs of debian.  I see it says pip is missing so I'll try to fix that first.

pip was missing.  Both boards are debian jammy if that helps.

**Comment by wesalmon** [comment]
Silly me!  I am not sure how I missed the error that octo was not installed or how the script continued.  
The issue was missing pip.  The image I am using is from the armbian.org site so I am guessing they don't include pip in the current version?
All is good now on the rock64.  I'll start by installing pip on the orange pi 2 and I'm sure it will be successful.
Thank you sir!

**Comment by wesalmon** [comment]
Issue resolved by installing pip first.

**Comment by paukstelis** [comment]
The script should install pip (python3-pip). If it doesn't, that's an error.

**Comment by wesalmon** [comment]
I'll be running it again in just a few on a new board and I'll let you know.

**Comment by wesalmon** [comment]
I just re-ran on an orangepi zero 2 with no issues.  The missing pip must
have been a miss from the rock64 image.  I had no issues with a clean
install this time.
I have a second rock64 I'll try in a few days and let you know if your
script picks up the pip upgrade or not.

Thank you!
