### ISSUE TITLE
Little "pacman --needed" fix

### ISSUE THREAD

**Issue by git4rker** [paukstelis/octoprint_deploy#129]
On most Arch Linux systems base-devel packages are already installed and it's a pain to redownload all of them with slow internet connection.

So adding --needed argument prevents pacman from reinstalling packages that are already installed.

**Comment by KeithCu** [comment]
I just did a pull request for this:
https://github.com/paukstelis/octoprint_deploy/pull/137

This looks like a great tool, even for single instance installs. Thank you!

**Comment by git4rker** [comment]
Heh, I use Mainsail now but I'm still happy that someone payed attention to my issue.

I guess I will close it, as the PR is already there.

**Comment by KeithCu** [comment]
I've not installed OctoPrint yet, but I discovered this great tool, that should probably be an official part of the OctoPrint project, for those who don't use the pre-configured images.
