### ISSUE TITLE
haproxy update needed in your script

### ISSUE THREAD

**Issue by Bradford1040** [paukstelis/octoprint_deploy#135]
I personally didn't use your script, I took the long road lol, (didn't know about your script till way after)

` reqrep ^([^\ :]*)\ /(.*)     \1\ /\2`

above needs to be changed to below

`http-request replace-path  ^([^\ :]*)\ /(.*)     \1\ /\2`

I do believe `reprep` is depreciated

**Comment by paukstelis** [comment]
The script determines the haproxy version and uses the appropriate syntax.
