### ISSUE TITLE
Independent printers

### ISSUE THREAD

**Issue by fabiomaticus** [paukstelis/octoprint_deploy#15]
I have two printers with two octoprint instanze. I noticed that if one is printing and I turn off the other, automatically the active one freezes and you lose your job.

**Comment by paukstelis** [comment]
This shouldn't happen and I have never seen it happen. Please provide octoprint.log files right for both instances after this happens. Are you using AUTO for detecting the serial port, or are you using the octo_[instance] name for connecting to the printers?

**Comment by fabiomaticus** [comment]
Hello. I didn't select AUTO and each printer connects to its own USB instance (/dev/octo_INSTANCE)

**Comment by paukstelis** [comment]
You will need to provide some logs for each of your instances to look into why this happens.
