### ISSUE TITLE
Prepare on base raspbian

### ISSUE THREAD

**Issue by ToyVo** [paukstelis/octoprint_deploy#16]
I wanted to run this on a base raspbian 64 bit lite install, but there is no prepare specifically for it and the ones for Ubuntu/Mint do not work, apt suggests using libjpeg62-turbo-dev instead  of libjpeg8-dev.
Once I installed the dependencies manually and picked one of the existing OSs, because it continues even if it fails to install, it did work just fine, but I feel like this might be a valid OS option to add

**Comment by paukstelis** [comment]
Thanks. I will take a look shortly.
