### ISSUE TITLE
Firmware update prerequisites

### ISSUE THREAD

**Issue by nagyrobi** [paukstelis/octoprint_deploy#181]
Dear @paukstelis thanks for your work!

I'd like to use the [Firmware Updater Plugin](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/), specifically the marlinbft flash method.

In the plugin config dialog, in the Prerequisite Status section I get the message "Python `marlin-binary-protocol` package is NOT installed". Instructions to install are [here](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/devel/doc/marlinbft.md).

When I try to run `pip3 install marlin-binary-protocol` as my normal user logged in onto my debian system, I get:
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

Please instruct how to install the package correctly. Thanks.

**Comment by paukstelis** [comment]
Likely you have to run pip from the virtual environment:
`/home/$USER/OctoPrint/bin/pip3 install marlin-binary-protocol`
