### ISSUE TITLE
cant delete instances

### ISSUE THREAD

**Issue by LehmannADL** [paukstelis/octoprint_deploy#22]
trying to delete my lulzbot instance. when i select delete it just reloads on linux. can select or delete.

**Comment by paukstelis** [comment]
Is it an instance that you made using the script? You can check which instances have been created with: cat /etc/octoprint_instances

**Comment by thirtyxarcher** [comment]
I'm having a similar issue where I created instances but they don't show up in the Delete menu. 
![image](https://user-images.githubusercontent.com/17993415/177653808-b8a7d76a-585f-43d3-a6ce-54b7f1feced8.png)
![image](https://user-images.githubusercontent.com/17993415/177653899-7bb5ef7b-b068-4881-b430-f4fd7272eedb.png)

**Comment by paukstelis** [comment]
That's interesting. I'll have a look into it

**Comment by paukstelis** [comment]
Turned out to be very simple. I used :alnum: regex when I should have used :graph: to take in account punctuation characters. Changes pushed. To update simply: `git -C octoprint_deploy pull` then try and delete instance.
