### ISSUE TITLE
Problem wiht Add New instance

### ISSUE THREAD

**Issue by fabiomaticus** [paukstelis/octoprint_deploy#29]
I want to add a new instance. I run the command sudo octoprint_deploy / octoprint_deploy.sh
I click on "Add Instance", but it repeats the question over and over again.
![Immagine 2022-07-25 165119](https://user-images.githubusercontent.com/32363332/180806555-3973b5d7-49d3-47f6-aca8-4b4906ec4649.png)

**Comment by paukstelis** [comment]
This is because your octoprint_deploy version is newer than the version used to do the system prepare. The solution is to make a file called octoprint_deploy in /etc that contains the necessary information.

The contents should look like this:
```
type: linux/octopi
streamer: ustreamer/mjpg-streamer
haproxy: true/false
```
where you select the correct option for each line

**Comment by fabiomaticus** [comment]
can you help me? I don't know what to do!

**Comment by paukstelis** [comment]
Yes, I can try. First, are you using linux (ubuntu, etc.) or octopi?

**Comment by fabiomaticus** [comment]
Octopi

**Comment by paukstelis** [comment]
OK, then do the following from an ssh/putty session on the RPi:
`sudo nano /etc/octoprint_deploy`
Then paste the following:
```
type: octopi
streamer: mjpg-streamer
haproxy: true
```
then Ctrl+X to save the file.

**Comment by fabiomaticus** [comment]
Now, sudo octoprint_deploy / octoprint_deploy.sh

**Comment by paukstelis** [comment]
Yes.

**Comment by fabiomaticus** [comment]
^I have this problem
![Immagine 2022-07-25 180635](https://user-images.githubusercontent.com/32363332/180824285-8571e55f-dc11-4e02-9866-dea4c7fa42c9.png)

**Comment by paukstelis** [comment]
That is also an issue from preparing the system with an older version.

`sudo apt install  uuid-runtime` in the terminal should fix.

You could remove the instance and reinstall it if you want  to, but it will likely work without issue (unless you use home assistant or or something that requires unique ids).

**Comment by fabiomaticus** [comment]
Many thanks. It works perfectly without sending new commands. I offer you a coffee. Many thanks again.
