### ISSUE TITLE
SimplyPrint cloud plugin

### ISSUE THREAD

**Issue by kasperhvid** [paukstelis/octoprint_deploy#32]
Not sure if this is a OctoDeploy problem or SP problem - but when you chose to let OD install SP - and then configure the first printer - then the instances get confused with eachother and instance #2 thinks its instance #1

**Comment by paukstelis** [comment]
That's in the SimplyPrint pipeline, not octoprint_deploy.

**Comment by punassuming** [comment]
@paukstelis is it even possible / supported to connect two deployed instances to simplyprint? It looks like they just follow an IP address and not the subdomain definition that octoprint_deploy provides.

**Comment by kasperhvid** [comment]
It very much is! My printfarm runs up to 6 instances per pi with octo deploy
