### ISSUE TITLE
FFMPEG path missing in timelapse 

### ISSUE THREAD

**Issue by natewils** [paukstelis/octoprint_deploy#36]
I enjoyed the ease of install but my question is for octolapse, it is missing "path to FFMPEG" this field is empty , I have tried to add /usr/bin/avconv and /usr/bin/FFMPEG and there is no path found, any help is appreciated

**Comment by paukstelis** [comment]
It is `/usr/bin/ffmpeg`. Linux executable commands are typically not uppercase.

**Comment by natewils** [comment]
Thank you so much all the help I found was exactly how I pasted it, thanks again
