### ISSUE TITLE
UPS Plugin

### ISSUE THREAD

**Issue by skl111** [paukstelis/octoprint_deploy#50]
I am using this with 2 printers and I have a UPS for each one, how would I manually configure the UPS plugin to talk to them, it sees 2 of them, but nothing passes to the plugin.,
any ideas?

**Comment by paukstelis** [comment]
which plugin is it?

**Comment by paukstelis** [comment]
Sorry, I don't have any way of testing the UPS plugin. It probably needs NUT to be configured in such a way that you have a unique identifier for each UPS which can then get passed to the plugin.

**Comment by skl111** [comment]
I have nut configured and each UPS has a uniqe ID that shows up in the UPS plugin

**Comment by paukstelis** [comment]
Sorry, you might try OctoPrint Discord or forums. I have no experience with that plugin or NUT.

**Comment by skl111** [comment]
ok, thank you
