### ISSUE TITLE
not an issue just a question

### ISSUE THREAD

**Issue by nncrypted** [paukstelis/octoprint_deploy#51]
Is it possible to add haproxy after a fully set up and configured system? I was trouble shooting some camera issues so I removed the entire setup reinstalled without haproxy then realized MY mistake with the cameras and now rather than reinstalling everything would like to just install haproxy. Is this possible without full reinstall?

**Comment by paukstelis** [comment]
Not in an automated way, I'm afraid. It could be done manually, but it would be a fair bit of editing /etc/haproxy.cfg

**Comment by nncrypted** [comment]
Ok no problem thanx for the quick response.
