### ISSUE TITLE
I can't erase backups

### ISSUE THREAD

**Issue by Vidorlp** [paukstelis/octoprint_deploy#56]
Hello, as I have been configuring Octoprint I have been making backups for security, now I have 6 backup that I do not need and that I would like to erase. I access the menu and in the Backup & Restore option, the backup appear but I cannot eliminate them individually or with the option of Select All. Use Debian in an old laptop. I have looked at the log and says nothing about this problem.

[https://github.com/paukstelis/octoprint_install/issues/6](url)

**Comment by paukstelis** [comment]
I'm afraid I misunderstood your original question about backups. If you are doing backups within the OctoPrint UI, octoprint_deploy is not involved at all. This is a question for the OctoPrint forum.
