### ISSUE TITLE
/etc/sudoers.d/octoprint-service:1:14: syntax error

### ISSUE THREAD

**Issue by ajaybnl** [paukstelis/octoprint_deploy#62]
I am getting error while installing some .sh files.

/etc/sudoers.d/octoprint-service:1:14: syntax error

Brief: 

pi@ajayoctoprint:~$ sudo lsb_release -a
/etc/sudoers.d/octoprint-service:1:14: syntax error
pi ALL= (ALL): /bin/systemctl restart octoprint.service
             ^
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Comment by paukstelis** [comment]
octoprint_deploy does not make a file called octoprint-service in sudoers.d. You either tried to do some manual installation for installed from some other source.
