### ISSUE TITLE
Error With CMAKE (Ubuntu Server 21.10)

### ISSUE THREAD

**Issue by mon5termatt** [paukstelis/octoprint_deploy#7]
![image](https://user-images.githubusercontent.com/43628254/155877527-b3484800-40c5-4c6e-b86f-d4dcb2feebfe.png)

**Comment by mon5termatt** [comment]
this is on first install, new machine, installed 10 minutes before

**Comment by paukstelis** [comment]
Those are all warnings, not errors. Everything should still work
