### ISSUE TITLE
Feature Request: Plugin/cloud streaming service recommendations

### ISSUE THREAD

**Issue by dburr** [paukstelis/octoprint_deploy#72]
Hi, I just heard about this tool from Chris' Basement. Very grateful for its existence. I don't as yet have multiple printers, but I am sure that day will come sooner or later (probably sooner ;-) ) and when that day comes, this will be extremely useful.

Here are some suggestions for additional plugins and/or cloud streaming services to add to the recommended plugins and streaming services list:

- [Obico](https://plugins.octoprint.org/plugins/obico/) (formerly known as The Spaghetti Detective.) Remote printer monitoring and AI-driven failure detection.
- [Auto Login Config](https://plugins.octoprint.org/plugins/autologin_config/) lets you set up OctoPrint to auto log you in if you are coming in from a local network. Would be nice if the octoprint_deploy script itself could actually do the configuration of this plugin for you (i.e. using Linux tools to glean your local IP address/subnet and automatically filling those in.)

**Comment by paukstelis** [comment]
Thanks for the suggestions. I am not going to be adding a significant number of plugins to these lists. It is trivial to install plugins, and keep in mind that if you install a plugin in one instance, it will be available to ALL instances once they are restarted (i.e. you only have to install once).
