### ISSUE TITLE
Camera Not Working

### ISSUE THREAD

**Issue by pekote** [paukstelis/octoprint_deploy#81]
I'm trying to setup octoprint in ubuntu, this script works excellent but the webcam does not start, I tried different cameras with no luck. My camera  is a generic Hercules and works fine with Cheese. 
I tried to setup octoprint several times from fresh ubuntu installations with mjpg streamer or ustreamer 

This is my latest attempt with mjpg streamer-> 

peko@pekoubnt:~$ sudo systemctl status cam_PrusaCesimar
● cam_PrusaCesimar.service - the OctoPi(buntu) webcam daemon with the user specified config
     Loaded: loaded (/etc/systemd/system/cam_PrusaCesimar.service; enabled; preset: enabled)
     Active: active (running) since Fri 2023-05-05 09:50:29 -03; 25min ago
   Main PID: 10550 (mjpg_streamer)
      Tasks: 7 (limit: 4566)
     Memory: 544.0K
        CPU: 6ms
     CGroup: /system.slice/cam_PrusaCesimar.service
             └─10550 /home/peko/mjpg-streamer/mjpg_streamer -i "input_uvc.so -d /dev/cam_PrusaCesimar -r 640x480 -f 5 -timeout 30" -o "output_http.so -p 8001"

May 05 09:50:30 pekoubnt mjpg_streamer[10550]:  o: username:password....: disabled
May 05 09:50:30 pekoubnt mjpg_streamer[10550]: MJPG-streamer [10550]: username:password....: disabled
May 05 09:50:30 pekoubnt mjpg_streamer[10550]:  o: commands.............: enabled
May 05 09:50:30 pekoubnt mjpg_streamer[10550]: MJPG-streamer [10550]: commands.............: enabled
May 05 09:50:30 pekoubnt mjpg_streamer[10550]: MJPG-streamer [10550]: starting input plugin input_uvc.so
May 05 09:50:30 pekoubnt mjpg_streamer[10550]: MJPG-streamer [10550]: starting output plugin: output_http.so (ID: 00)
May 05 09:51:00 pekoubnt mjpg_streamer[10550]:  i: select() timeout
May 05 09:51:00 pekoubnt mjpg_streamer[10550]:  i: cleaning up resources allocated by input thread
May 05 09:51:00 pekoubnt mjpg_streamer[10550]: MJPG-streamer [10550]: select() timeout
May 05 09:51:00 pekoubnt mjpg_streamer[10550]: MJPG-streamer [10550]: cleaning up resources allocated by input thread
peko@pekoubnt:~$

**Comment by paukstelis** [comment]
Try restarting the camera service: `sudo systemctl restart cam_PrusaCesimar`
