### ISSUE TITLE
After OctoPrint deploy, I get this "The OctoPrint server is currently not running"

### ISSUE THREAD

**Issue by tonyatrre** [paukstelis/octoprint_deploy#9]
After loading OctoPrint was able to load the octopi.local page, but after trying to install OctoPrint deploy, I get this "The OctoPrint server is currently not running".    Could not download log from SSH cause it says "Permission denied". I'm using a fresh 32gb mini SD, tried lots of fresh installs, reseted many times, same results.  I spend the last 3 night trying every possibility I can find online or YouTube and no such luck.   Can you please help me

**Comment by paukstelis** [comment]
octoprint_deploy intentionally turns off the server on port 5000 after you setup the admin user and install a new instance. That original instance is only a template for making new instances. You should be able to connect to any new instance you have made at http://octopi.local/instancename/ OR http://octopi.local:5001 (or 5002, 5003, etc. depending on how many instance you have made)
