### ISSUE TITLE
missing command uuidgen running raspberry pi buster

### ISSUE THREAD

**Issue by KyferEz** [paukstelis/octoprint_deploy#90]
Getting this error when setting up first printer using Raspberry Pi OS:
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian

![image](https://github.com/paukstelis/octoprint_deploy/assets/770397/a6586570-b219-43ed-84b3-826f162b63b3)

![image](https://github.com/paukstelis/octoprint_deploy/assets/770397/d380314d-3695-43fb-9308-0330e3f88118)

Found this which seems related: https://forums.raspberrypi.com/viewtopic.php?t=268239

**Comment by paukstelis** [comment]
Unfortunately, they have given it a different name. Try: `sudo apt install uuid-runtime`
It is a non-critical error, so your instance should be fine, unless you want to reinstall it.

**Comment by KyferEz** [comment]
Paul, thank you, that worked!
